### ISSUE TITLE
Code checking with different version of MinkowskiEngine

### ISSUE THREAD

**Issue by tonghe90** [chrischoy/SpatioTemporalSegmentation#22]
I check out the newest version of MinkowskiEngine, but the training process is quite different from the previous version(c52ba2f). Could you please check the code for scannet segmentation

**Comment by tonghe90** [comment]
The loss curve is quite different (previous is better), and the newest version fails to load 4 examples in a batch, while the previous is ok

**Comment by chrischoy** [comment]
Hi Tong,

Could you pull from the SpatioTemporalSegmentation repository master as well?

The possible cause of the issue is that we prepend the batch indices before the coordinates from ME v0.4 (https://stanfordvl.github.io/MinkowskiEngine/sparse_tensor.html#MinkowskiEngine.SparseTensor.SparseTensor) and I updated the SpatioTemporalSegmentation repository as well.

In general, it is discouraged to directly generate batched coordinates or get decomposed coordinates. Please refer to the warning section of the [Sparse Tensor API](https://stanfordvl.github.io/MinkowskiEngine/sparse_tensor.html#MinkowskiEngine.SparseTensor.SparseTensor) to make your code up-to-date with the latest Minkowski Engine.
