### ISSUE TITLE
MinkowskiNet42

### ISSUE THREAD

**Issue by ShengyuH** [chrischoy/SpatioTemporalSegmentation#4]
hi Christopher,

Thank you for your great work and also open source the code!

In your paper you use MinkowskiNet42 to indicate the network architecture you use for Scannet semantic segmentation task. Is this the same as Res16UNet34C？ I'm trying to reproduce the result but seems there's still a long way from 0.73. Can you tell me your batch size?

**Comment by chrischoy** [comment]
Yes, sorry for the confusing name. ResUNet34C has 42 layers, but is derived from ResNet34 and it goes up to tensor stride 16, hence the name Res16UNet34.

I used batch_size 9. During the training, it reaches 70% validation, fluctuates heavily first due to high lr, but then converges to 71~72% validation almost at the end of the first phase. The second phase is pretty redundant unless you aim for the benchmark.
